[versions]
kotlin = "2.2.20"
kordex = "2.3.5-MIKBOT.1-SNAPSHOT"
kmongo = "5.5.1"
coroutines = "1.10.2"
serialization = "1.9.0"
ktor = "3.3.0"
kord = "mikbot-SNAPSHOT"
api = "5.0.2"
ksp = "2.2.20-2.0.3"
lavakord = "9.1.5"
kordex-plugin = "1.7.3"
kompendium = "4.0.4-SNAPSHOT"

[libraries]
kord-common = { group = "dev.kord", name = "kord-common", version.ref = "kord" }
kord-rest = { group = "dev.kord", name = "kord-rest", version.ref = "kord" }
kord-core = { group = "dev.kord", name = "kord-core", version.ref = "kord" }
kordex = { group = "dev.kordex", name = "kord-extensions", version.ref = "kordex" }
kordex-unsafe = { group = "dev.kordex.modules", name = "dev-unsafe", version.ref = "kordex" }
kordex-processor = { group = "dev.kordex", name = "annotation-processor", version.ref = "kordex" }
kordx-emoji = { group = "dev.kord.x", name = "kordx.emoji", version = "feature-mpp-SNAPSHOT" }
kotlinx-coroutines-jdk8 = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-jdk8", version.ref = "coroutines" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version = "0.7.1-0.6.x-compat" }
kmongo-coroutine-serialization = { group = "org.litote.kmongo", name = "kmongo-coroutine-serialization", version.ref = "kmongo" }
kmongo-id-serialization = { group = "org.litote.kmongo", name = "kmongo-id-serialization", version.ref = "kmongo" }
stdx-full = { group = "dev.schlaubi", name = "stdx-full", version = "1.3.0" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version = "1.5.18" }
google-apis-youtube = { group = "com.google.apis", name = "google-api-services-youtube", version = "v3-rev20250714-2.0.0" }
lavakord-kord = { group = "dev.schlaubi.lavakord", name = "kord", version.ref = "lavakord" }
lavakord-sponsorblock = { group = "dev.schlaubi.lavakord", name = "sponsorblock", version.ref = "lavakord" }
lavakord-lavsrc = { group = "dev.schlaubi.lavakord", name = "lavasrc-jvm", version.ref = "lavakord" }
lavakord-lavasearch = { group = "dev.schlaubi.lavakord", name = "lavasearch-jvm", version.ref = "lavakord" }
lavakord-lyrics = { group = "dev.schlaubi.lavakord", name = "lyrics-jvm", version.ref = "lavakord" }
lavalink-protocol = { group = "dev.arbjerg.lavalink", name = "protocol", version = "4.1.1" }
ksp-api = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }
ktor-resources = { group = "io.ktor", name = "ktor-resources", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-auth = { group = "io.ktor", name = "ktor-client-auth", version.ref = "ktor" }
ktor-client-resources = { group = "io.ktor", name = "ktor-client-resources", version.ref = "ktor" }
ktor-server-content-negotiation = { group = "io.ktor", name = "ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty", version.ref = "ktor" }
ktor-server-resources = { group = "io.ktor", name = "ktor-server-resources", version.ref = "ktor" }
ktor-server-status-pages = { group = "io.ktor", name = "ktor-server-status-pages", version.ref = "ktor" }
ktor-server-auth = { group = "io.ktor", name = "ktor-server-auth", version.ref = "ktor" }
ktor-server-auth-jwt = { group = "io.ktor", name = "ktor-server-auth-jwt", version.ref = "ktor" }
ktor-server-sessions = { group = "io.ktor", name = "ktor-server-sessions", version.ref = "ktor" }
ktor-server-core = { group = "io.ktor", name = "ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-cors = { group = "io.ktor", name = "ktor-server-cors", version.ref = "ktor" }
ktor-server-websockets = { group = "io.ktor", name = "ktor-server-websockets", version.ref = "ktor" }
ktor-server-html-builder = { group = "io.ktor", name = "ktor-server-html-builder", version.ref = "ktor" }
ktor-server-swagger = { group = "io.ktor", name = "ktor-server-swagger", version.ref = "ktor" }
kompendium-core = { group = "io.bkbn", name = "kompendium-core", version.ref = "kompendium" }
kompendium-resources = { group = "io.bkbn", name = "kompendium-resources", version.ref = "kompendium" }

kubernetes-client = { group = "io.kubernetes", name = "client-java", version = "24.0.0" }
kotlin-jsonpatch = { group = "io.github.reidsync", name = "kotlin-json-patch", version = "1.0.0" }

pf4j = { group = "org.pf4j", name = "pf4j", version = "3.13.0" }
pf4j-update = { group = "org.pf4j", name = "pf4j-update", version = "2.3.0" }

gson = { group = "com.google.code.gson", name = "gson", version = "2.13.2" }

koin = { group = "io.insert-koin", name = "koin-core", version = "4.1.1" }

asm = { group = "org.ow2.asm", name = "asm", version = "9.8" }

mikbot-api = { group = "dev.schlaubi", name = "mikbot-api" }
bucket4j = { group = "com.bucket4j", name = "bucket4j_jdk17-lettuce", version = "8.15.0" }

kordex-gradle-plugin = { group = "dev.kordex.gradle.plugins", name = "kordex", version.ref = "kordex-plugin" }
gradle-license-report = { group = "com.github.jk1", name = "gradle-license-report", version = "2.9" }

lettuce-core = { group = "io.lettuce", name = "lettuce-core", version = "6.8.1.RELEASE" }

[plugins]
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinx-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
gradle-publish = { id = "com.gradle.plugin-publish", version = "2.0.0" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version = "5.6.8" }
mikbot = { id = "dev.schlaubi.mikbot.gradle-plugin", version = "1.0.0" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
