[versions]
kordex = "1.5.5.3-MIKBOT-SNAPSHOT"
kmongo = "4.7.0"
pf4j = "3.7.0"
coroutines = "1.6.4"
serialization = "1.3.3"
ktor = "2.1.0"
kord = "0.8.x-SNAPSHOT"

[libraries]
kord-core = { group = "dev.kord", name = "kord-core", version.ref = "kord" }
kordex = { group = "com.kotlindiscord.kord.extensions", name = "kord-extensions", version.ref = "kordex" }
kordex-unsafe = { group = "com.kotlindiscord.kord.extensions", name = "unsafe", version.ref = "kordex" }
kordex-processor = { group = "com.kotlindiscord.kord.extensions", name = "annotation-processor", version.ref = "kordex" }
kordx-emoji = { group = "dev.kord.x", name = "emoji", version = "0.5.0" }
kotlinx-coroutines-jdk8 = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-jdk8", version.ref = "coroutines" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
kmongo-coroutine-serialization = { group = "org.litote.kmongo", name = "kmongo-coroutine-serialization", version.ref = "kmongo" }
kmongo-id-serialization = { group = "org.litote.kmongo", name = "kmongo-id-serialization", version.ref = "kmongo" }
pf4j = { group = "org.pf4j", name = "pf4j", version.ref = "pf4j" }
stdx-full = {group = "dev.schlaubi", name = "stdx-full", version = "1.2.1" }
envconf = { group = "dev.schlaubi", name = "envconf", version = "1.1" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version = "1.2.11" }
commons-text = { group = "org.apache.commons", name = "commons-text", version = "1.9" }
google-cloud-bom = { group = "com.google.cloud", name = "libraries-bom", version = "26.0.0" }
google-cloud-translate = { group = "com.google.cloud", name = "google-cloud-translate" }
google-apis-youtube = { group = "com.google.apis", name = "google-api-services-youtube", version = "v3-rev20220719-2.0.0" }
lavakord-kord = { group = "dev.schlaubi.lavakord", name = "kord", version = "3.6.3" }
spotify = { group = "se.michaelthelin.spotify", name = "spotify-web-api-java", version = "7.1.0" }
krontab = { group = "dev.inmo", name = "krontab", version = "0.8.0" }
ksp-api = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version = "1.7.10-1.0.6" }
rhino = { group = "org.mozilla", name = "rhino", version = "1.7.14" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-server-content-negotiation = { group = "io.ktor", name = "ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty", version.ref = "ktor" }
ktor-server-resources = { group = "io.ktor", name = "ktor-server-resources", version.ref = "ktor" }
ktor-server-status-pages = { group = "io.ktor", name = "ktor-server-status-pages", version.ref = "ktor" }
ktor-server-auth = { group = "io.ktor", name = "ktor-server-auth", version.ref = "ktor" }
ktor-server-sessions = { group = "io.ktor", name = "ktor-server-sessions", version.ref = "ktor" }
ktor-server-core = { group = "io.ktor", name = "ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-html-builder = { group = "io.ktor", name = "ktor-server-html-builder", version.ref = "ktor" }
github-repositories = { group = "dev.nycode.github", name = "repositories", version = "1.0.0-SNAPSHOT" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version = "0.4.0" }
java-string-similarity = { group = "info.debatty", name = "java-string-similarity", version = "2.0.0" }
